- name: Install system pkgs
  become: true
  pacman:
    name:
      - git
      - base-devel
      - openssh
  tags:
    - install
    - core
- name: Clone yay
  ansible.builtin.git:
    repo: "https://aur.archlinux.org/yay.git"
    dest: "/tmp/yay"
  tags:
    - install
    - core
    - yay
- name: Install yay
  become: false
  shell: "cd /tmp/yay && makepkg --noconfirm -si"
  tags:
    - install
    - core
    - yay
- name: Install core deps
  pacman:
    name:
      - cmake
      - unzip
      - ninja
  tags:
    - install
    - core
